### ISSUE TITLE
cannot import name 'rfc3161' from 'pyasn1_modules'

### ISSUE THREAD

**Issue by packmad** [ralphje/signify#22]
It looks like that the `pyasn1_modules` is broken.
I understand that it is not a problem of signify, but maybe you can set a working version in the requirements.txt 

```
$ pip3 install signify
$ python3

>>> f = open('example.pe', 'rb')
>>> pefile = SignedPEFile(f)
>>> pefile.verify()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/signify/signed_pe.py", line 239, in verify
    signed_datas = list(self.signed_datas)
  File "/usr/local/lib/python3.8/dist-packages/signify/signed_pe.py", line 213, in signed_datas
    from .authenticode import AuthenticodeSignedData
  File "/usr/local/lib/python3.8/dist-packages/signify/authenticode.py", line 32, in <module>
    from pyasn1_modules import rfc3161, rfc2315, rfc5652
ImportError: cannot import name 'rfc3161' from 'pyasn1_modules' (/usr/lib/python3/dist-packages/pyasn1_modules/__init__.py)
>>> from pyasn1_modules import rfc3161, rfc2315, rfc5652
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'rfc3161' from 'pyasn1_modules' (/usr/lib/python3/dist-packages/pyasn1_modules/__init__.py)
```

**Comment by packmad** [comment]
My bad, I didn't activate the venv, is working... sorry!
